# Generated by Django 3.2.4 on 2021-06-22 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=70)),
                ('lastname', models.CharField(default='', max_length=70)),
                ('phonenumber', models.IntegerField(default='')),
                ('salary', models.FloatField(default='', max_length=70)),
                ('role', models.CharField(default='', max_length=70)),
                ('department', models.CharField(default='', max_length=70)),
                ('joindate', models.CharField(default='', max_length=70)),
            ],
        ),
    ]
